on: [push]
jobs:
  test-project:
    runs-on: ['ubuntu-latest', 'macos-latest']
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
      - run: pip install pytest
      - run: make
      - run: pytest

